name: 'Setup Node and pnpm'
description: 'Installs Node and pnpm for use in workflows'

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '20'
        cache: 'pnpm'