name: Create docker image
description: Image name to deploy

inputs:
  app:
    description: App to be deployed (client or server)
    required: true

outputs:
  image_to_deploy:
    value: ${{ steps.get_image.outputs.image_to_deploy }}
    description: Image name to deploy

runs:
  using: "composite"
  steps:
    - name: Define image to deploy
      id: get_image
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      shell: bash
      run: |
        VERSION=$(jq -r '.version' apps/${{ inputs.app }}/package.json)
        TAG=${VERSION}_$BRANCH_NAME
        echo "TAG=$TAG"
        IMAGE_TO_DEPLOY=etherealpulse.azurecr.io/${{ inputs.app }}:$TAG
        echo "image_to_deploy=$IMAGE_TO_DEPLOY" >> $GITHUB_OUTPUT