name: 'Restore cache'
description: 'Retrieves cached node modules and build artifacts'

runs:
  using: 'composite'
  steps:
    - name: Restore node modules
      uses: actions/cache/restore@v4.0.2
      id: cache-node-modules
      with:
        fail-on-cache-miss: true
        key: node_modules-${{ hashFiles('pnpm-lock.lock') }}
        path: |
          node_modules/
          apps/*/node_modules/
          sdks/*/node_modules/

    - name: Restore builds
      uses: actions/cache/restore@v4.0.2
      id: cache-builds
      with:
        fail-on-cache-miss: true
        key: cache-builds-${{ hashFiles('apps/**', 'sdks/**', '!sdks/java') }}
        path: |
            apps/client/build/
            apps/server/dist/
            sdks/*/lib/