name: Build Docker Compose Image

on:
  push:
    paths:
      - 'docker-compose.yml'
      - 'apps/client/**'
      - 'apps/server/**'
  pull_request:
    paths:
      - 'docker-compose.yml'
      - 'apps/client/**'
      - 'apps/server/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Compose images
        run: docker-compose -f docker-compose.yml build
