name: Server build and deploy

on:
  push:
    branches:
      - main
    paths:
      - "apps/server/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/apps/server
          registryUrl: etherealpulse.azurecr.io
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: ethereal-pulse-server
          containerAppEnvironment: container-apps-enviroment
          resourceGroup: RG-Ethereal-Pulse
          location: westeurope
          targetPort: ${{ secrets.MS_PORT }}
          ingress: external
          environmentVariables: PORT=${{ secrets.MS_PORT }} DATABASE_URI=${{ secrets.DATABASE_URI }} CLOUD_PROVIDER_NAME=${{ secrets.CLOUD_PROVIDER_NAME }} AZURE_CONNECTION_STRING=${{ secrets.AZURE_CONNECTION_STRING }}
