name: Deploy to Azure Container Instances

on:
  push:
    branches:
      - main
    paths:
      - 'apps/server/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        uses: azure/docker-login@v1
        with:
          login-server: etherealpulse.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f apps/server/Dockerfile . -t etherealpulse.azurecr.io/myapp:${{ github.sha }}
          docker push etherealpulse.azurecr.io/myapp:${{ github.sha }}

      # Debug and Verification Steps
      - name: Check for existing ACI and delete (if any)
        run: |
          echo "Checking for existing Azure Container Instances..."
          az container delete --resource-group RG-Ethereal-Pulse --name myapp-${{ github.sha }} --yes || true
          echo "Existing Azure Container Instance deleted (if existed)."

      - name: Verify Deletion
        run: |
          echo "Verifying the deletion of the container instance..."
          if az container show --resource-group RG-Ethereal-Pulse --name myapp-${{ github.sha }} 2>/dev/null; then
            echo "Error: Container instance still exists!"
            exit 1
          else
            echo "Container instance does not exist. Proceeding with deployment."
          fi

      - name: Deploy to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: RG-Ethereal-Pulse
          name: myapp-${{ github.sha }}
          dns-name-label: myapp-${{ github.sha }}
          image: etherealpulse.azurecr.io/myapp:${{ github.sha }}
          registry-login-server: etherealpulse.azurecr.io
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          location: "westeurope"
          environment-variables: |
            PORT=${{ secrets.MS_PORT }}
            DATABASE_URI=${{ secrets.DATABASE_URI }}
            CLOUD_PROVIDER_NAME=${{ secrets.CLOUD_PROVIDER_NAME }}
            AZURE_CONNECTION_STRING=${{ secrets.AZURE_CONNECTION_STRING }}

      # Final Debug Statement After Deployment
      - name: Post-deployment check
        run: |
          echo "Deployment complete. Verifying deployment..."
          az container show --resource-group RG-Ethereal-Pulse --name myapp-${{ github.sha }}
